### ISSUE TITLE
session is active before topology was loaded

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/scylla-go-driver#188]
```
2022/04/08 11:35:13 cluster: open control connection
2022/04/08 11:35:13 [addr=[::1]:9042 shard=0] connected
2022/04/08 11:35:13 cluster: refresh topology
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1045250ac]

goroutine 1 [running]:
github.com/mmatczuk/scylla-go-driver/transport.(*ConnPool).LeastBusyConn(0x14000076258?)
        /Users/michal/Scylla/scylla-go-driver/transport/pool.go:66 +0x1c
github.com/mmatczuk/scylla-go-driver/transport.(*Node).LeastBusyConn(...)
        /Users/michal/Scylla/scylla-go-driver/transport/node.go:32
github.com/mmatczuk/scylla-go-driver.(*Session).leastBusyConn(0x10456ec80?)
        /Users/michal/Scylla/scylla-go-driver/session.go:128 +0xb0
github.com/mmatczuk/scylla-go-driver.(*Query).Exec(0x14000169c18)
        /Users/michal/Scylla/scylla-go-driver/query.go:15 +0x48
main.prepareKeyspaceAndTable(0x1400011a6e0?)
        /Users/michal/Scylla/scylla-go-driver/experiments/cmd/benchtab/main.go:98 +0x98
main.main()
        /Users/michal/Scylla/scylla-go-driver/experiments/cmd/benchtab/main.go:26 +0x120
exit status 2
```

**Comment by Kulezi** [comment]
Relates to #222, but I think now session can't be active before loading topology, but #222 still needs to be fixed.
