### ISSUE TITLE
panic: couldn't find given keyspace in current topology

### ISSUE THREAD

**Issue by mmatczuk** [mmatczuk/scylla-go-driver#246]
```
2022/05/27 10:27:48 Starting the benchmark
panic: couldn't find given keyspace in current topology

goroutine 299 [running]:
main.benchmark.func1()
	github.com/mmatczuk/scylla-go-driver/experiments/cmd/benchtab/main.go:95 +0x6ab
created by main.benchmark
	github.com/mmatczuk/scylla-go-driver/experiments/cmd/benchtab/main.go:71 +0xa9
```

**Comment by mmatczuk** [comment]
It seems that sometimes benchmark starts before topology is ready.

**Comment by mmatczuk** [comment]
It seems the benchmarks broke keyspace management in Scylla. It works with a different keyspace
